//
//  HomeInteractor.swift
//  Imaging
//
//  Created by Raymond Law on 7/7/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func fetchEntries(request: Home.FetchEntries.Request)
  func setIcon(request: Home.SetIcon.Request)
}

protocol HomeDataStore
{
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker = HomeWorker()
  
  // MARK: Fetch entries
  
  private var entries = [Entry]()
  
  func fetchEntries(request: Home.FetchEntries.Request)
  {
    worker.fetchEntries { (entries) in
      self.entries = entries
      let response = Home.FetchEntries.Response(entries: entries)
      presenter?.presentFetchEntries(response: response)
    }
  }
  
  // MARK: Set icon
  
  func setIcon(request: Home.SetIcon.Request)
  {
    var entry = entries[request.indexPath.row]
    entry.icon = request.icon
    
    // TODO: Persist the image
    
    let response = Home.SetIcon.Response(entry: entry, indexPath: request.indexPath)
    presenter?.presentSetIcon(response: response)
  }
}
